export const FHIR_BASE = "https://hapi.fhir.org/baseDstu3";

export const RESOURCE_TYPE = {
  Patient: "Patient",
  Practitioner: "Practitioner",
  Location: "Location",
  Appointment: "Appointment"
};

export const APPOINTMENT_HINT = {
  NO_HINT: "NO_HINT",
  LOCATION_HINT: "LOCATION_HINT",
  LOCATION_VALUE: "LOCATION_TEXT",
  PRACTITIONER_HINT: "PRACTITIONER_HINT",
  PRACTITIONER_VALUE: "PRACTITIONER_VALUE",
  CUSTOMER_HINT: "CUSTOMER_HINT",
  CUSTOMER_VALUE: "CUSTOMER_VALUE",
  APPOINTMENT_HINT: "APPOINTMENT_HINT",
  REASON_HINT: "REASON_HINT"
};

export const APPOINTMENT_HINT_LEVELS = [
  APPOINTMENT_HINT.NO_HINT,
  APPOINTMENT_HINT.APPOINTMENT_HINT,
  APPOINTMENT_HINT.REASON_HINT,
  APPOINTMENT_HINT.CUSTOMER_HINT,
  APPOINTMENT_HINT.CUSTOMER_VALUE,
  APPOINTMENT_HINT.PRACTITIONER_HINT,
  APPOINTMENT_HINT.PRACTITIONER_VALUE,
  APPOINTMENT_HINT.LOCATION_HINT,
  APPOINTMENT_HINT.LOCATION_VALUE
];

export const CHECK_IN_HINT = {
  NO_HINT: "NO_HINT",
  PATIENT: "PATIENT_HINT",
  CLICK: "CLICK_HINT",
  ID: "ID_HINT"
};

export const CHECK_IN_HINT_LEVELS = [
  CHECK_IN_HINT.NO_HINT,
  CHECK_IN_HINT.PATIENT,
  CHECK_IN_HINT.CLICK,
  CHECK_IN_HINT.ID
];

export const SECRET_IDENTIFIER = "555555-555";
export const SECRET_NAME = "Santa";
